 ---
apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ include "chart.fullname" . }}
  labels:
    app:  {{ include "chart.fullname" . }}
  annotations:
    reloader.stakater.com/match: "true"
data:
  agnhost-app.conf: |-
    location /agnhost {
        resolver local=on;
        rewrite ^/agnhost(?:/(.*))?$ /$1 break; 
        set $upstream http://agnhost-service.myns.svc.cluster.local:8080;
        proxy_pass $upstream;
        include    /usr/local/openresty/nginx/conf/proxy.conf;
    }
  http-echo.conf: |-
    location /http-echo {
        resolver local=on;
        set $upstream http://http-echo.myns.svc.cluster.local:5678;
        proxy_pass $upstream;
        include /usr/local/openresty/nginx/conf/proxy.conf;
    }
  simple-python-api.conf: |-
    location /books {
        set $app_upstream_var http://simple-python-api-service.myns.svc.cluster.local:8000;
        proxy_pass $app_upstream_var;
        include /usr/local/openresty/nginx/conf/proxy.conf;
    }