 ---
apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ include "chart.fullname" . }}
  labels:
    app:  {{ include "chart.fullname" . }}
  annotations:
    reloader.stakater.com/match: "true"
data:
  health.conf: |-
    location /health {
      access_log off;
      default_type application/json;
      return 200 '{"status":"UP"}';
    }